### ISSUE TITLE
JobID Reddundency

### ISSUE THREAD

**Issue by gfenoy** [opengeospatial/wps-rest-binding#100]
When we get the [JobList.yml ](https://raw.githubusercontent.com/opengeospatial/wps-rest-binding/master/core/openapi/responses/JobList.yaml) or use the status location to poll the current status, we have the id and jobID that provide the same information. One time we use the id in the returned JSON object and on the other we use it in the URL. Hence I don't see why the jobID is here.

Examples: 
 * Jobs list: 
    * https://demo.mapmint.com/WPS5/processes/OTB.BandMath/jobs
    * https://demo.mapmint.com/WPS5/processes/OTB.BandMath/jobs.html
 * Job status location: 
    * https://demo.mapmint.com/WPS5/processes/OTB.BandMath/jobs/11fb6472-0886-11eb-b160-525400a77789
    * https://demo.mapmint.com/WPS5/processes/OTB.BandMath/jobs/11fb6472-0886-11eb-b160-525400a77789.html

**Comment by bpross-52n** [comment]
Discussion from 2020-11-02 telecon: 

Rename infos to info in jobInfo.yaml

**Comment by bpross-52n** [comment]
The jobInfo element originated from here: #26. Removing the id from the jobInfo and renaming infos to info results in something like this:

```
[
	{
		"info": {
			"status": "successful",
			"jobID": "963078b5-a143-4d01-b918-9cc627c9b6a2",
			"links": [
				{
					"href": "http://localhost:8080/javaps/rest/processes/org.n52.javaps.test.EchoProcess/jobs/963078b5-a143-4d01-b918-9cc627c9b6a2",
					"rel": "status",
					"type": "application/json",
					"title": "Status document"
				},
				{
					"href": "http://localhost:8080/javaps/rest/processes/org.n52.javaps.test.EchoProcess/jobs/963078b5-a143-4d01-b918-9cc627c9b6a2/results",
					"rel": "results",
					"type": "application/json",
					"title": "Job results"
				}
			]
		}
	},
	{
		"info": {
			"status": "successful",
			"jobID": "bb3c2330-52e8-481a-9a01-c4cdc234a902",
			"links": [
				{
					"href": "http://localhost:8080/javaps/rest/processes/org.n52.javaps.test.EchoProcess/jobs/bb3c2330-52e8-481a-9a01-c4cdc234a902",
					"rel": "status",
					"type": "application/json",
					"title": "Status document"
				},
				{
					"href": "http://localhost:8080/javaps/rest/processes/org.n52.javaps.test.EchoProcess/jobs/bb3c2330-52e8-481a-9a01-c4cdc234a902/results",
					"rel": "results",
					"type": "application/json",
					"title": "Job results"
				}
			]
		}
	}
]
```

So I suggest to directly use an array of statusInfo elements for the job list and to remove the jobInfo element completely.

**Comment by gfenoy** [comment]
I wonder if it is still relevant/necessary to keep the object with a single attribute "info". So, I think it would be good to replace the current [jobInfo.yaml](https://raw.githubusercontent.com/opengeospatial/wps-rest-binding/master/core/openapi/schemas/jobInfo.yaml) by the current [statusInfo.yaml](https://raw.githubusercontent.com/opengeospatial/wps-rest-binding/master/core/openapi/schemas/statusInfo.yaml). 

We have two options to simplify and remove one level:

 1) we can rename the yaml file statusInfo to jobInfo, 
 2) change the reference in [jobList.yaml](https://raw.githubusercontent.com/opengeospatial/wps-rest-binding/master/core/openapi/schemas/jobList.yaml) to replace the reference to jobInfo.yaml by a reference to statusInfo.yaml.

In case we use one of the option, it would lead to something looking like the following which is the same but, with one level removed:
 
<pre>
<code>
[
	{
		"status": "successful",
		"jobID": "963078b5-a143-4d01-b918-9cc627c9b6a2",
		"links": [
			{
				"href": "http://localhost:8080/javaps/rest/processes/org.n52.javaps.test.EchoProcess/jobs/963078b5-a143-4d01-b918-9cc627c9b6a2",
				"rel": "status",
				"type": "application/json",
				"title": "Status document"
			},
			{
				"href": "http://localhost:8080/javaps/rest/processes/org.n52.javaps.test.EchoProcess/jobs/963078b5-a143-4d01-b918-9cc627c9b6a2/results",
				"rel": "results",
				"type": "application/json",
				"title": "Job results"
			}
		]
	},
	{
		"status": "successful",
		"jobID": "bb3c2330-52e8-481a-9a01-c4cdc234a902",
		"links": [
			{
				"href": "http://localhost:8080/javaps/rest/processes/org.n52.javaps.test.EchoProcess/jobs/bb3c2330-52e8-481a-9a01-c4cdc234a902",
				"rel": "status",
				"type": "application/json",
				"title": "Status document"
			},
			{
				"href": "http://localhost:8080/javaps/rest/processes/org.n52.javaps.test.EchoProcess/jobs/bb3c2330-52e8-481a-9a01-c4cdc234a902/results",
				"rel": "results",
				"type": "application/json",
				"title": "Job results"
			}
		]
	}
]
</pre>
</code>
