### ISSUE TITLE
WPS dataType field in literalDataDomain is too vague

### ISSUE THREAD

**Issue by pvretano** [opengeospatial/wps-rest-binding#13]
The definition of the dataType field in literalDataDomain.yaml is just a plain string.   This seems too vague since there is no way to point to a controlled vocabulary of data type names.  In TB14 the definition of the dataType field was an object that included the fields "name" and "reference" where reference was a URI pointing to controlled vocabulary or a definition of the type.  Another approach would be to define a enumeration of data types buy I feel the reference to a controlled vocabulary is more flexible.

**Comment by bpross-52n** [comment]
Fixed.
