### ISSUE TITLE
Differences in WPS schemas used in TB14 EOC versus schemas defined here

### ISSUE THREAD

**Issue by pvretano** [opengeospatial/wps-rest-binding#14]
As a general comment, that paths defined here and in the WPS used in TB14 for the ADES (see: https://github.com/opengeospatial/D009-ADES_and_EMS_Results_and_Best_Practices_Engineering_Report/blob/master/code/ades_wpst.json) seem pretty well aligned but the request and response body schemas differ quite significantly in some places.  It seems that the TB14 schemas align more closely with the XML schemas from WPS 2.0 while the schemas here seem to be simplified in some places.  Am I missing something or was this apparent simplification intentional?

I am definitely not opposed to simplifying things!   The reason I ask is that I am trying to update my TB14 EOC WPS implementation to align with the specification defined here but am finding it hard in some places to support both variations and I have to choose one or the other schema.  For the time being I am choosing to default to what is defined here (thus breaking my ADES with respect to TB14) but before I go too far down that rabbit hole I want to scope out what that plan are moving forward.  Are there any plans to try and reconcile any differences between the two schemas?

One example of the differences is with respect to literal input types.  The two schemas in this respect seem similar but scratching a little deeper exposes some big differences!  For example, in TB14 there is a "literalDataDomains" property which is an array of "literalDataDomainType" but there is not such construct in the schemas here.  In this respect the TB14 schemas seem more closely aligned with the XML schemas which have an unbounded cardinality on the LiteralDataDomain element.

**Comment by bpross-52n** [comment]
Hey Peter, I think we should align with the TB14 ADES/ the WPS 2.0 XML schemas. I will make an update this week.

**Comment by gfenoy** [comment]
From what I can see from the ADES implementation, they are supporting additionalParameters.

From my understanding,  a requests to a rest-binding implementation should give back the same kind  of metadata informations that can be available when using XML encoding. 

For instance, if a DescribeProcess request in version 2.0 of the WPS is providing a node then I should find a JSON object corresponding to this node, every  attribute from a node should become an attribute and so on...

So here is a very basic sample:

 - [WPS 2.0 GetDescribeProcess for a useless HelloPy2 example service](https://demo.mapmint.com/cgi-bin/zoo_loader.cgi?request=DescribeProcess&service=wps&version=2.0.0&Identifier=HelloPy2)
 - [Corresponding HelloPy2 description in JSON format](https://demo.mapmint.com/WPS2/processes/HelloPy2).

Unfortunately, I have tried to add a new [additionalParameters.yaml](https://github.com/gfenoy/wps-rest-binding/blob/master/core/openapi/schemas/additionalParameter.yaml) but I guess that I don't know how to proceed properly as the result seems to not [validate](https://apidevtools.org/swagger-parser/online/) against openapi spec...

Any help would be very welcome in refining this additionalParameters definition.

On another hand, I feel that  this should fall back to the new "OGC API -  Common" as it was defined in [ows-common](http://schemas.opengis.net/ows/2.0/owsAdditionalParameters.xsd) schema before.
