### ISSUE TITLE
Do we need values with metadata references (e.g. UOM)?

### ISSUE THREAD

**Issue by pvretano** [opengeospatial/wps-rest-binding#16]
A number of definitions in the schemas, for example dataType and uom, are defined as simple strings.  Do we need codespaces OR references for these definitions in order to point to some normative vocabulary or code list for these values?  For example, saying  "uom": "m" might benefit from having a reference to where uom came from.  For example: "uom": { "name": "m", "reference": "http://..." }.

In the XML schemas, this was actually inherited from OWS Common which defined ows:DataType and ows:UOM as strings with a "reference" attribute that allowed for referring metadata about the value.

**Comment by bpross-52n** [comment]
Fixed.
