### ISSUE TITLE
provide response without WPS wrapper

### ISSUE THREAD

**Issue by tomkralidis** [opengeospatial/wps-rest-binding#21]
Are there examples of an Execute request/response pattern asking for the actual data payload without the WPS response wrapping?  Use case is running a process to return `text/csv` with a CSV dump of a timeseries.

**Comment by bpross-52n** [comment]
Hi Tom, you mean something like raw data output in WPS 2.0? That is not specified for the REST binding.. One way to solve this would be to request the data as reference. The reference then should point directly to the data.

**Comment by tomkralidis** [comment]
Thanks @bpross-52n makes sense.  What about adding a vendor specific extension to the API which won't break the spec?

**Comment by bpross-52n** [comment]
Yeah, that would be one option. We did some experiments with a path "processes/{processId}/jobs/{jobId}/result/{resultId}" to obtain a single result. This could then be delivered without the WPS wrapper. I think it was dropped because it was not specified in the WPS 2.0 standard. But we are moving away from this anyway, so this could maybe be introduced again...

**Comment by tomkralidis** [comment]
+1 for this approach, and it's a good time to revisit.

**Comment by francbartoli** [comment]
> Yeah, that would be one option. We did some experiments with a path "processes/{processId}/jobs/{jobId}/result/{resultId}" to obtain a single result. This could then be delivered without the WPS wrapper. I think it was dropped because it was not specified in the WPS 2.0 standard. But we are moving away from this anyway, so this could maybe be introduced again...

+1 it makes sense also for me, I would just consider the plural form:

`processes/{processId}/jobs/{jobId}/results/{resultId}`

**Comment by gfenoy** [comment]
I am very supportive to offer a way to select one specific result and its format.

Nevertheless, I don't understand the solution proposed here.

Indeed, let suppose that we add this `{resultId}` parameter to access one result from a result set produced over a service execution then, what shall be the result provided to the client when requesting? For me, it can still be included inside a JSON object or as RawDataOutput.

I think we may consider using the [RFC 7240](https://tools.ietf.org/html/rfc7240#page-9) which is defining the Preference header and more specifically on section 4.2 where we can find the two following options:
 * "return=representation" 
 * "return=minimal"

In case we introduce this Preference header then the client shall be able to choose in between the different representation of the result by using one of this option. (Obviously this only apply to this `/result/{resultId}` url and cannot be applied to upper level -  `/result` cause there may be multiple result set)

**Comment by spacebel** [comment]
in execute request, attribute response=raw seems to be there for that.

**Comment by gfenoy** [comment]
> in execute request, attribute response=raw seems to be there for that.

I was not able to find it, where is this request parameter and its relevant possible values are defined exactly?

**Comment by alaisslx** [comment]
> > Yeah, that would be one option. We did some experiments with a path "processes/{processId}/jobs/{jobId}/result/{resultId}" to obtain a single result. This could then be delivered without the WPS wrapper. I think it was dropped because it was not specified in the WPS 2.0 standard. But we are moving away from this anyway, so this could maybe be introduced again...
> 
> +1 it makes sense also for me, I would just consider the plural form:
> 
> `processes/{processId}/jobs/{jobId}/results/{resultId}`

Based on the discussion in the back briefing Thurstay evening:
Could the explicit result URL that references a single output also be used as input for a chained process?

With the URL it would the be the responsibility of the chained process to request / retrieve the data. As implementation optimisation, Processes running with access to the same cache (e.g. same process, machine, cluster, whatever) could look up the result directly, avoiding marshalling or transfer if possible.

**Comment by spacebel** [comment]
> > in execute request, attribute response=raw seems to be there for that.
> 
> I was not able to find it, where is this request parameter and its relevant possible values are defined exactly?

This is indeed missing on the current spec (but was implemented by all servers in Testbed 14 ).
https://github.com/opengeospatial/wps-rest-binding/commit/04e9db70cd48edb6606549543b73459170785ffe

**Comment by spacebel** [comment]
Using output reference, the /result document looks like this:

```
{
   "outputs":[
      {
         "mimeType":"image/tiff",
         "href":"http://some-host/WPS/xxxYYY",
         "id":"output1"
      },
      {
         "mimeType":"image/tiff",
         "href":"http://some-host/WPS/xxxYYY",
         "id":"output2"
      }
   ]
}
```

**Comment by bpross-52n** [comment]
Response attribute (raw/document) is back in the current execute.yaml
