### ISSUE TITLE
How to you describe an input with minOccurs=1 and maxOccurs=unbounded?

### ISSUE THREAD

**Issue by pvretano** [opengeospatial/wps-rest-binding#22]
If I have a process input that has an unbounded cardinality, how do I describe that?  maxOccurs is defined as an integer so we could either put in a very large integer or define a special value (e.g. -2) to mean unbounded.   Neither of these solution is very satisfying to me.  My prefered solution would be to define maxOccurs as:

"maxOccurs": {
   "oneOf": [
      { "type": "integer"  },
      { "type": "string", "const": "unbounded"}
   ]
}
 NOTE: the use of the "const" key is new in the latest draft of the JSON schema specification.  We could also use "enum": ["unbounded"] to fix the value.

**Comment by spacebel** [comment]
agreed

**Comment by bpross-52n** [comment]
Any views on this approach? 
https://github.com/opengeospatial/wps-rest-binding/issues/49

**Comment by bpross-52n** [comment]
"unbounded" string is allowed for maxOccurs.
