### ISSUE TITLE
About the valueDefinition references from literalDataDomain 

### ISSUE THREAD

**Issue by gfenoy** [opengeospatial/wps-rest-binding#24]
It seems that the [literalDataDomain.yaml](https://github.com/opengeospatial/wps-rest-binding/blob/master/core/openapi/schemas/literalDataDomain.yaml) from (https://github.com/opengeospatial/wps-rest-binding/commit/d3a7ad5903a5f5e832d0f6431695944426d4023d) is wrong.

The `valueDefinition` defined in [literalDataDomain.yaml](https://github.com/opengeospatial/wps-rest-binding/blob/master/core/openapi/schemas/literalDataDomain.yaml) references 4 other yaml files but rather than using a filename it makes reference to another part of the document which is not existing (`/components/schemas/`).

So, replacing the following: `$ref: '#/components/schemas/X'` with `$ref: X.yaml` should solve this issue.

**Comment by bpross-52n** [comment]
Thanks Gérald, I will fix this right away.
