### ISSUE TITLE
Response model for HTTP GET of jobs should provide more information about the status

### ISSUE THREAD

**Issue by francbartoli** [opengeospatial/wps-rest-binding#26]
Returning only the list of jobs unique identifiers is useless if I want to filter them by status.
For example, if I want to retrieve all successful executed processes I have to loop over all the retrieved jobs and perform additional GET calls for each of them to get the status. All of this client side.

**Comment by francbartoli** [comment]
@gfenoy I've seen your proposal which is reasonable for me, just one question: why the plural form `infos`?

**Comment by gfenoy** [comment]
@francbartoli I should admit that I wonder why I used this name, status would probablby be better.

**Comment by spacebel** [comment]
I vote for.

**Comment by bpross-52n** [comment]
Retrieving the job collection with additional information is a separate requirements class in the current draft.
