### ISSUE TITLE
Are reference values missing from the schema?

### ISSUE THREAD

**Issue by ghobona** [opengeospatial/wps-rest-binding#27]
An example of when a reference value might be useful is when importing complex data as Input.

Looking at the schema it does not appear to allow that.

**valueType.yaml** imports **referenceValue.yaml**

However the file in the repo appears to be named **valuesReference.yaml**

Are reference values missing from the schema?

**Comment by bpross-52n** [comment]
There is also a **referenceValue.yaml**, see here: https://github.com/opengeospatial/wps-rest-binding/blob/master/core/openapi/schemas/referenceValue.yaml
**valuesReference.yaml** is used to describe literal data domains.

**Comment by ghobona** [comment]
That's great! Thanks.
