### ISSUE TITLE
Trailing ‘/‘ in /processes/{id}/

### ISSUE THREAD

**Issue by ghobona** [opengeospatial/wps-rest-binding#28]
In line 82 of the file openapi.yaml, there is a trailing `/` on the path `/processes/{id}/` ?

It appears to be the only path with a `/` at the end.

Is it necessary?

**Comment by m-mohr** [comment]
I think it should be removed.

**Comment by bpross-52n** [comment]
That was an artifact, fixed in 32193a28945c867d039f683eca8c8af732a8b259

**Comment by ghobona** [comment]
ok, thanks.
