### ISSUE TITLE
Callback extension for asynchronous execution

### ISSUE THREAD

**Issue by mneagul** [opengeospatial/wps-rest-binding#31]
An extension supporting triggers according to job status, particularly the user/client should be able to specify triggers for conditions like:

- `onSuccess`: Url to be triggered upon process completion. The trigger should have access to job status and output information.
- `onFail`: URL to be triggered on process failure 
- `progressUpdate`: URL to be triggered by the job while progressing and should contain progress status (eg. proccent of job completion)

With a bit of clever hacking this could be used to create DAGs/workflows/process chaining. Also this would be useful for microservice based applications

**Comment by spacebel** [comment]
Notifications has been implemented by Peter Vretanos in TB14. 
This is a very interesting extension of what has been specified.

**Comment by m-mohr** [comment]
Would that be a URL to call, which means the client would need to spin up a HTTP server? Or would it be rather a publish/subscribe based protocol, for example based on WebSockets?

**Comment by mneagul** [comment]
> Would that be a URL to call, which means the client would need to spin up a HTTP server? 

Only if it needs to be called back by the processing. The URL could be another application doing some additional operations (eg. updating a database, etc).

Another potentially interesting operation implementable using triggers would be the ability of starting another processing/job after the completion of the current job. This would effectively allow implementing workflows.

> Or would it be rather a publish/subscribe based protocol, for example based on WebSockets?

I think that would be to elaborate to be included as an extension of the standard.

**Comment by spacebel** [comment]
Submitted the support of callback relying on openAPI callbacks in the API document.
https://github.com/opengeospatial/wps-rest-binding/commit/8cc2bdaf6483af7d8c5a85c7ad0a45b8e68cc4b6

**Comment by bpross-52n** [comment]
Additional requirements class for callbacks is now included in the draft.
