### ISSUE TITLE
Links in Job Status required?

### ISSUE THREAD

**Issue by m-mohr** [opengeospatial/wps-rest-binding#39]
The links property in the status page for a job (`GET /processes/{id}/jobs/{jobID}`) is required, but it doesn't say what to add. So I'd say it should either not be required or explicitly state what should be added (e.g. link to results and exceptions).

**Comment by bpross-52n** [comment]
Its not required, I will remove it. Also an articfact..

**Comment by bpross-52n** [comment]
Done.
