### ISSUE TITLE
Specify synchronous execution

### ISSUE THREAD

**Issue by bpross-52n** [opengeospatial/wps-rest-binding#40]
Specify synchronous execution.

- Either use a query parameter or a HTTP header to specify the execution mode.
- Return a [result](https://github.com/opengeospatial/wps-rest-binding/blob/master/core/openapi/schemas/result.yaml) object. 
- Do not return a header with the location (as there technically is no location, i.e. its a temporary job)

I would be glad about suggestions on how to specify this with OpenAPI. Could this be formalized somehow or do we need a textual description?

See also #30

**Comment by spacebel** [comment]
I'm in favor of keeping the original input parameter, as implemented in TB14: https://github.com/opengeospatial/wps-rest-binding/commit/04e9db70cd48edb6606549543b73459170785ffe 

For the response, it makes sense to get the Result document as a response.

**Comment by m-mohr** [comment]
This is how openEO describes synchronous execution: https://open-eo.github.io/openeo-api/v/0.4.1/apireference/#tag/Batch-Job-Management/paths/~1result/post
Just for inspiration...

**Comment by spacebel** [comment]
Duplicate #30 discussion . Let's keep the reference in the other issue ticket ok ?
