### ISSUE TITLE
Notes on Hackathon WPS Implementations

### ISSUE THREAD

**Issue by sima-qian** [opengeospatial/wps-rest-binding#46]
During the hackathon I was attempting to build a JS client that would act as an interactive GUI for any WPS API. I mostly developed against [52North's API](http://geoprocessing.demo.52north.org:8080/javaps/rest) as it had the most content to test against with regard to processes. When attempting to interact with [Helyx's](http://wps-helyx.westeurope.azurecontainer.io:5600/) and [Peter's](http://www.pvretano.com/cubewerx/cubeserv/default/wps/2.0.0?f=application%2Fjson) implementations, I came across inconsistencies between the services:

#### **General**
- Peter's API required the page format to be encoded in the URL (i.e `f=application/json`) -- the default behaviour is to return XML
  - the other APIs returned JSON and required no such parameters
  - JSON by default is highly preferable, from the point of view of a JS client
- I was hoping to use a module like [traverson](https://www.npmjs.com/package/traverson) and its extension [traverson-hal](https://www.npmjs.com/package/traverson-hal) to 'walk' over the APIs, but this was not possible as the APIs are not [HAL-compliant](https://tools.ietf.org/id/draft-kelly-json-hal-06.txt)

#### **`/processes`**
- one API had the key `processVersion`, while the other two went with `version`
- is the `title` attribute supposed be a human-readable value?
- the link to the process endpoint was defined differently:
  - Peter's API had the link under the attribute `processDescriptionURL`, whereas Helyx and 52North's were found at `links[n].href` where `links` holds an array of objects
    - on a related note, is there a use case where there is more than one link?
- 52North defined a type on the link; Helyx and Peter did not

#### **`/processes/${id}`**
- the definition of inputs varied across the implementations
  - on Helyx's service, they were found at `inputs[n].formats` or `inputs[n].literalDataDomains`
  - on Peter's service they were at `inputs[n].additionalParameters`
  - 52North had the definition at `inputs[n].input.formats` or `inputs[n].input.literalDataDomains`
- Helyx specified the `format` even when also defining the input under `literalDataDomains`; 52North did not

**Comment by spacebel** [comment]
Hi. Indeed all implementations from Testbed 14 follow the following spec: https://raw.githubusercontent.com/spacebel/testbed14/master/json-spec/wps-t_tb14_spacebel-v1.6.yaml

Additional properties is only providing additional information for project specific reasons.

Our server is at : http://34.77.240.214/ades-proxy/

**Comment by pvretano** [comment]
Thanks for the feedback @sima-qian.  Much appreciated.  I am in the process of transition my server to the api definition used in TB14 to the one currently defined by the WPS SWG.  As @spacebel pointed out, you can safely ignore the additionalParameters.
