### ISSUE TITLE
Chaining processes - any ideas?

### ISSUE THREAD

**Issue by moa77** [opengeospatial/wps-rest-binding#53]
As of the wps 2 standard, chaining asynch processes has to be hacked. Any thoughts on including this in the new ogc api - processing standard?

**Comment by jerstlouis** [comment]
See #47

**Comment by jerstlouis** [comment]
Added more concrete details to #47 on ideas for fully intereoperable OGC API , based on Collections & Processes, following the Coverage & Analytics Code Sprint

**Comment by bpross-52n** [comment]
Discussion will continue here #47
