### ISSUE TITLE
processDescriptionURL to links array

### ISSUE THREAD

**Issue by tomkralidis** [opengeospatial/wps-rest-binding#7]
A given [process object](http://geoprocessing.demo.52north.org:8080/javaps/rest/processes/org.n52.wps.echoprocess.SelfDescribingEchoProcess) provides a `processDescriptionURL`.  To be more consistent with [WFS3](https://cdn.rawgit.com/opengeospatial/WFS_FES/3.0.0-draft.1/docs/17-069.html#_feature_collection_metadata), should we replace with `links`, which is a list of 1..n link objects (where the implementation can choose to explicitly reference a `process/{id}/` link accordingly) ?  Sample:

```json
    {
      "id": "org.n52.geoprocessing.jts.algorithm.JTSConvexHullAlgorithm",
      "title": "org.n52.geoprocessing.jts.algorithm.JTSConvexHullAlgorithm",
      "version": "1.1.0",
      "jobControlOptions": [
        "async-execute",
        "sync-execute"
      ],
      "outputTransmission": [
        "value",
        "reference"
      ],
      "links": [
        {
          "href": "http://geoprocessing.demo.52north.org:8080/javaps/rest/processes/org.n52.geoprocessing.jts.algorithm.JTSConvexHullAlgorithm",
          "type": "application/json",
          "hreflang": "en-US",
          "rel": "canonical",
          "title": "Process description"
        }
      ]
    }
```

**Comment by pvretano** [comment]
Hmmm ... must be a deviation for the OpenAPI document for WPS that we used inTB14.  In TB14 the process description included a links section.  See here: https://github.com/opengeospatial/D009-ADES_and_EMS_Results_and_Best_Practices_Engineering_Report/blob/master/code/ades_wpst.json

**Comment by bpross-52n** [comment]
In the ADES json it also seems to be just the processDescriptionURL, see here: https://github.com/opengeospatial/D009-ADES_and_EMS_Results_and_Best_Practices_Engineering_Report/blob/master/code/ades_wpst.json#L1660

But in general, I am ok with introducing a links element for the resources of a WPS, so the link process decription probably should be moved in there.
