### ISSUE TITLE
How to correctly document conformance?

### ISSUE THREAD

**Issue by fmigneault** [opengeospatial/wps-rest-binding#71]
Hi, 

CRIM is participating in many OGC-Testbeds and we have an EMS/ADES implementation (https://github.com/crim-ca/weaver) that supports the routes and schemas specified by these OGC-API docs. 
I would like to correctly report the `/conformance` route (https://github.com/crim-ca/weaver/issues/53) with the appropriate resources, but I'm having a hard time figuring out exactly what/how everything should be reported. 

I also cannot see any document under http://www.opengis.net/spec/WPS/, so links related to this are "blindly" added to our conformance, but I cannot validate them... 
I can see the ones under http://schemas.opengis.net/wps/ 
I have tried registering to http://www.opengis.net but got no answer/feedback.

Any help would be greatly appreciated.

**Comment by bpross-52n** [comment]
You would document conformance by listing the conformance classes under /conformance like for example:

{
	"conformsTo": [
		"http://www.opengis.net/spec/ogcapi-processes/1.0/conf/core",
		"http://www.opengis.net/spec/ogcapi-processes/1.0/conf/oas30",
		"http://www.opengis.net/spec/ogcapi-processes/1.0/conf/job-collection",
		"http://www.opengis.net/spec/ogcapi-processes/1.0/conf/json",
		"http://www.opengis.net/spec/ogcapi-processes/1.0/conf/html"
	]
}

**Comment by fmigneault** [comment]
For the moment I've got the following. 

    conformance = {"conformsTo": [
        # "http://www.opengis.net/spec/wfs-1/3.0/req/core",
        # "http://www.opengis.net/spec/wfs-1/3.0/req/oas30",
        # "http://www.opengis.net/spec/wfs-1/3.0/req/html",
        # "http://www.opengis.net/spec/wfs-1/3.0/req/geojson",
        "http://schemas.opengis.net/wps/1.0.0/",
        "http://schemas.opengis.net/wps/2.0/",
        "http://www.opengis.net/spec/WPS/2.0/req/service/binding/rest-json/core",
        # "http://www.opengis.net/spec/WPS/2.0/req/service/binding/rest-json/oas30",
        # "http://www.opengis.net/spec/WPS/2.0/req/service/binding/rest-json/html"
        "https://github.com/opengeospatial/wps-rest-binding",
    ]}
    return HTTPOk(json=conformance)

I can add the links you provided, but I'm not too sure what the `html` one includes. Is it https://github.com/opengeospatial/wps-rest-binding/tree/master/core/requirements/html ? 
If so, what does supporting `text/html` implies. and more specifically, how are the otherwise JSON body rendered in the HTML body?

Thanks

**Comment by bpross-52n** [comment]
This seem to be old URIs. But in the case of the OGC API - Processes, the URIs are not fixed yet, anyway. Also, it is not specified how to render JSON in HTML. It is not mandatory to support this.

**Comment by fmigneault** [comment]
In our case we support both the old WPS and the new OGC API-Processes variants, so I prefer to report all conformance links.
Is there any approximate plan on when the URI will be fixed? I feel this would help early adoption of the new interfaces by developers.
Thanks for your help.

**Comment by bpross-52n** [comment]
I think the URIs are fixed only after the OGC Naming Authority has approved them in the process of officially releasing the standard. Hopefully this will happen this year.

**Comment by ghobona** [comment]
@fmigneault The example in https://github.com/opengeospatial/wps-rest-binding/issues/71#issuecomment-628530417 is closer to what the conformance class URIs will be. There might be some minor changes when the draft specification goes for Public Comment.

Please note as well that WFS 3.0 is now officially called OGC API - Features - Part 1: Core, since 2018. The approved conformance class URIs for it can be found at http://docs.opengeospatial.org/is/17-069r3/17-069r3.html#_declaration_of_conformance_classes

**Comment by ghobona** [comment]
The revised conformance URIs are shown at https://htmlpreview.github.io/?https://github.com/opengeospatial/wps-rest-binding/blob/master/docs/18-062.html#trueresponse-3
