### ISSUE TITLE
Job creation response sync requirement needs a bit of clean-up.

### ISSUE THREAD

**Issue by pvretano** [opengeospatial/wps-rest-binding#75]
The following requirements needs a bit of clean-up ...

https://github.com/opengeospatial/wps-rest-binding/blob/master/core/requirements/core/REQ_job-creation-response-sync.adoc

Specifically, the point about the exception response should be removed or moved to another requirement about the failure response.
Also, we might consider making this is multi-part requirement.  Part A is that the server returns a 200.  Part B is about the content of the response if the response is wrapped in a JSON array.  Part C is about the response if a single raw data response is requested.
... or, we could consider breaking these out into multiple requirements.

**Comment by bpross-52n** [comment]
Done.
