### ISSUE TITLE
Only members can be submitters

### ISSUE THREAD

**Issue by ogcscotts** [opengeospatial/wps-rest-binding#78]
https://github.com/opengeospatial/wps-rest-binding/blob/master/core/clause_0_front_material.adoc

Per policy, only OGC Members can be listed as "submitters." Please remove the "member" column from the table, remove the non-member from the official submitters, then create a new clause "vi. Acknowledgements" and in that clause recognize the contribution of any non-members,

**Comment by bpross-52n** [comment]
Actually the submitter is a member, but the organization not. So would it be ok to just remove the member column in this case?

**Comment by gfenoy** [comment]
Dear Benjamin,
I am very sorry for such a burden and additional work on your side…

Thanks a lot for trying.

Have great week-end.

Best regards,
Gerald Fenoy
gerald.fenoy@geolabs.fr

GEOLABS
Siège social :
Futur Building I
1280, avenue des Platanes
34970 Lattes
Tél. fixe : +33 (0) 4 67 43 09 95
Tél. portable : +33 (0) 6 70 08 25 39

**Comment by ogcscotts** [comment]
@bpross-52n @gfenoy OK, great - I should have checked the portal membership first! Yes, just remove that column and attribute Gerald to his membership organization.
