### ISSUE TITLE
Submit SWG Charter to the TC for approval

### ISSUE THREAD

**Issue by ghobona** [opengeospatial/wps-rest-binding#79]
The **draft** OGC API - Processes SWG charter is at https://github.com/opengeospatial/wps-rest-binding/blob/master/charter/OGC-API-Processes-SWG-Charter.adoc

**Comment by bpross-52n** [comment]
In the encodings section the charter states that "No encoding will be mandatory and other encodings.." 

The current draft states that the JSON encoding **is** mandatory, e.g. for resources like the landing page, the conformance list, the list of processes and the status info. This needs to be resolved. Probably the JSON encoding must not be mandatory, as it originates from the GeoJSON requirements class of the API Features, and that class was used for features/feature collections.

**Comment by ghobona** [comment]
SWG decision on 2020-06-15 that the charter will be updated to make JSON encoding mandatory, consistent with the draft specification.

**Comment by m-mohr** [comment]
The link above is broken.

**Comment by bpross-52n** [comment]
Undergoing the formal process now. Charter available at: https://portal.ogc.org/files/?artifact_id=93963&version=1
