### ISSUE TITLE
processes/{id} should not have a root process object

### ISSUE THREAD

**Issue by tomkralidis** [opengeospatial/wps-rest-binding#8]
Example: http://geoprocessing.demo.52north.org:8080/javaps/rest/processes/org.n52.geoprocessing.jts.algorithm.JTSConvexHullAlgorithm

To be consistent with WFS3 the response should be only the object without the root `process` object.

**Comment by spacebel** [comment]
Disagreed
The root is a processOffering, which contains process, jobControls, and transmission mode.

Maybe the WPS 2.0 schemas should be reviewed, because indeed, it is confused that a describeProcess operation does not return a process, but a processOffering which contains a process...

**Comment by bpross-52n** [comment]
There are some resources that have a root element and some that don't have one (e.g. status info). Probably we should make this consistent..

**Comment by francbartoli** [comment]
@tomkralidis one note: the title should be renamed with `processes/{id} `, anyway I'm in favor of your comment. This also would be aligned with jobs which have:

GET `/processes/{id}/jobs`

gives:

```
{
    "jobs": [
        "d6c4d409-3218-4b71-86cb-689bf23fab7e",
        ...
    [
}
```

while

GET `/processes/{id}/jobs/{jobID}`

gives directly:

```
{
    "message": "Process finished",
    "links": [
        {
            "href": "http://localhost/api/v1/wps/processes/buffer/jobs/15124658-d48b-4333-acc7-8d2332f7d2fd",
            "rel": "self",
            "type": "application/json",
            "hreflang": "en-US",
            "title": "This document"
        },
        {
            "href": "http://localhost/api/v1/wps/processes/buffer/jobs/15124658-d48b-4333-acc7-8d2332f7d2fd/result",
            "rel": "result",
            "type": "application/json",
            "hreflang": "en-US",
            "title": "Process result"
        }
    ],
    "status": "successful",
    "progress": 100
}
```

without the root 

```
{
    "job": {}
}
```

**Comment by tomkralidis** [comment]
@francbartoli agree. In the spirit of OGC API Common, aligning these concepts will end up in very efficient clients and processing (in our case Python OWSLib's emerging OGC API support).

**Comment by spacebel** [comment]
I agree that response should not include the root element.

But the root element of the "describe process" response is not "process", but "process offering" which includes "jobControlOptions", "transmissionMode", "processVersion", "processModel" and "process".

I'm not against simplifying things, and the processOffering definition could be removed in profit of a simpler root  processType, but just to mention it would be a discrepancy with the XML spec. 
I also assume that the intent of the spec was to distinguish a Process with a ProcessOffering concept (the process in a particular version and published with particular allowed transmission mode etc.).

**Comment by francbartoli** [comment]
@spacebel I cannot explain this property https://github.com/opengeospatial/wps-rest-binding/blob/master/core/openapi/schemas/processOffering.yaml#L6 indeed from the `processOffering`

**Comment by bpross-52n** [comment]
Root elements were removed.
