### ISSUE TITLE
Invalid ref in openapi/responses/ProcessList yaml

### ISSUE THREAD

**Issue by justb4** [opengeospatial/wps-rest-binding#88]
[core/openapi/responses/ProcessList.yaml](https://github.com/opengeospatial/wps-rest-binding/blob/master/core/openapi/responses/ProcessList.yaml) contains an invalid ref:

```
      $ref: "https://raw.githubusercontent.com/opengeospatial/wps-rest-binding/master/core/openapi/schemas/processCollection.yaml"

```
This should be 
```
      $ref: "https://raw.githubusercontent.com/opengeospatial/wps-rest-binding/master/core/openapi/schemas/processList.yaml"

```

due to recent change from #86 for #82.

**Comment by bpross-52n** [comment]
Thanks for reporting this.

**Comment by justb4** [comment]
@bpross-52n thanks for very quick action!
