### ISSUE TITLE
Include a table early on that links to the various paths defined in the document...

### ISSUE THREAD

**Issue by pvretano** [opengeospatial/wps-rest-binding#9]
The WFS specification includes a table of paths in the front material (the abstract) that allows one to jump directly to the section in the specification describing that path.  We should consider adding something like that to the WPS standard as well.  For developers, it makes navigating the document much easier.  See here for an example: https://github.com/opengeospatial/WFS_FES/blob/master/core/standard/clause_0_front_material.adoc

**Comment by bpross-52n** [comment]
There is such a table in the overwiev section: https://github.com/opengeospatial/wps-rest-binding/blob/master/core/standard/clause_6_overview.adoc

We can move it to the abstract, I guess.

**Comment by pvretano** [comment]
Doh!  Completely missed that.  Yeah, moving more to the front might be better but don't do it if it is too much trouble! ;)  The important thing is that it is there.

**Comment by bpross-52n** [comment]
Overview table was moved up to the Abstract.
