### ISSUE TITLE
OpenAPI definition references JobCollection and ProcessCollection

### ISSUE THREAD

**Issue by ghobona** [opengeospatial/wps-rest-binding#97]
OpenAPI definition [example](https://app.swaggerhub.com/apis/geoprocessing/WPS/1.0-draft.3) references JobCollection.yaml and ProcessCollection.yaml, however these have been renamed JobList.yaml and ProcessList.yaml

Update the OpenAPI definition example to be consistent with the new names of the yaml files.

**Comment by bpross-52n** [comment]
Updated link, fixed references.
